#!/usr/bin/env python

import json
import sys
import base64
import mimetypes

filename = sys.argv[1]
with open(filename, "rb") as f:
    print(json.dumps({
        "filename": filename,
        "content-type": mimetypes.guess_type(filename)[0],
        "data": base64.b64encode(f.read()).decode()
    }))
